---
new_page_extension: md
auto_deploy: false
admin_path: "/static/admin"
webhook_url: 
sections:
- type: directory
  path: src/content/posts
  label: Posts
  create: documents
  match: "**/*"
  templates:
  - blog
- type: directory
  path: src/content/projects
  label: Projects
  create: all
  match: "**/*"
  templates:
  - project
upload_dir: projects
public_path: https://ukemi-website.s3.eu-west-2.amazonaws.com/projects
front_matter_path: ''
use_front_matter_path: 
file_template: ":filename:"
build:
  preview_env:
  - GHOST_API_URL=https://ghost.ukemi.ninja
  - GHOST_CONTENT_API_KEY=e5037d855bbb0bce6d260da37f
  - DEV_GHOST_API_URL=https://ghost.ukemi.ninja
  - DEV_GHOST_CONTENT_API_KEY=e5037d855bbb0bce6d260da37f
  preview_output_directory: public
  install_dependencies_command: npm install
  preview_docker_image: node:10
  mount_path: "/srv"
  working_dir: "/srv"
  instant_preview_command: npm run forestry:preview
